[package]
name = "aoc2025"
version = "0.1.0"
edition = "2024"

[dependencies]
glam = "0.30.9"
itertools = "0.14.0"
nom = "8.0.0"
rstest = "0.26.1"
tracing = "0.1.43"
tracing-subscriber = "0.3.22"

[dependencies.test-log]
version = "0.2.19"
features = ["trace", "color"]
default-features = false
